document.excel.path=C:/cientifica/Registro_CIEI2024.xlsx
document.word.template=C:/cientifica/plantillas/Aprobacion.docx
document.libreoffice.path=C:/Program Files/LibreOffice/program/soffice.exe
#document.libreoffice.path=C:/cientifica/LibreOffice/program/soffice.exe


# Directorio principal
documentos.base-path=C:/cientifica

# Archivo Excel
documentos.excel=Registro_CIEI2024.xlsx

# Directorio de plantillas
documentos.plantillas-path=plantillas

# Plantilla de Extensión
documentos.plantilla-extension=Extension.docx
documentos.plantilla-renovacion=Renovacion.docx
documentos.plantilla-enmienda=Enmienda.docx
documentos.plantilla-constancia-exenta=Exenta.docx
documentos.plantilla-constancia=Constancia.docx
documentos.plantilla-informe-avance=Informe_Avance.docx


# Archivo Excel Animal
documentos.excel.animal=CIEI-AB-CIENTIFICA 2026.xlsx

# Plantilla animal
documentos.plantilla.animal-aprobacion=Aprobacion-Animal.docx
documentos.plantilla.animal-enmienda=Enmienda-Animal.docx


