document.excel.path=C:/cientifica/Registro_CIEI2024.xlsx
document.word.template=C:/cientifica/documento.docx
document.libreoffice.path=C:/Program Files/LibreOffice/program/soffice.exe


# Directorio principal
documentos.base-path=C:/cientifica

# Archivo Excel
documentos.excel=Registro_CIEI2024.xlsx

# Directorio de plantillas
documentos.plantillas-path=plantillas

# Plantilla de Extensión
documentos.plantilla-extension=Extension.docx